name: perpustakaan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  get: 4.6.5
  flutter_easyloading: 3.0.5
  flutter_speed_dial: 6.2.0
  dropdown_button2: 1.9.2
  intl: 0.17.0
  syncfusion_flutter_datepicker: 20.4.43
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # 

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

